### ISSUE TITLE
Doesn't work on Linux x64

### ISSUE THREAD

**Issue by YorVeX** [YorVeX/ObsCSharpExample#2]
NativeAOT [doesn't support cross-compiling](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#cross-architecture-compilation), but the project includes script files to prepare a [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) environment and produce a Linux x64 build on Windows using this environment. This works fine and since the WSL environment is based on Ubuntu 20.04 it creates a Linux library linked against glibc 2.31 that should have a relatively good range of compatibility. However, the plugin produced that way crashes OBS on startup.

OBS does load the module (at least it's listed under loaded modules in the log) when it is stripped down to export the very basic obs_module_set_pointer, obs_module_ver and obs_module_load functions and these methods don't do anything except return the version (obs_module_ver) and true (obs_module_load). As soon as only the simple blogva call to produce a log message is made, the plugin makes OBS crash on startup.

I personally have no experience debugging applications on Linux and also no ambitions to extend my knowledge in that field. Any help figuring this out would be much appreciated and I would then port over any solutions to my other C# plugins like [xObsBeam](https://github.com/YorVeX/xObsBeam), [xObsAsyncImageSource](https://github.com/YorVeX/xObsAsyncImageSource) and [xObsBrowserAutoRefresh](https://github.com/YorVeX/xObsBrowserAutoRefresh) to make them available for Linux too.

**Comment by Slkoshka** [comment]
It works now with [NetObsBindings](https://github.com/kostya9/NetObsBindings) 0.0.1.33-alpha (tested on Ubuntu 20.04 in WSL, should work on a real system too) 🎉

I don't have time right now to make a PR, but the only changes that are needed is to update the package reference to a newer version and replace `ObsBase.blogva` call with `ObsBase.blog` (and remove the third `null` argument which is not needed anymore).

![image](https://user-images.githubusercontent.com/67478997/230742442-efb3dd7e-9dc1-412a-b33e-1c0cb065bc2e.png)

**Comment by YorVeX** [comment]
Thanks again for your work @Slkoshka ! Fixed with https://github.com/YorVeX/ObsCSharpExample/commit/1591bc78bb5677fb873bb207aa904ee530ec4d6b.

**Comment by YorVeX** [comment]
Also my other projects [xObsBeam](https://github.com/YorVeX/xObsBeam), [xObsAsyncImageSource](https://github.com/YorVeX/xObsAsyncImageSource) and [xObsBrowserAutoRefresh](https://github.com/YorVeX/xObsBrowserAutoRefresh) were updated now and they all passed a quick and dirty test in a Ubuntu VM.
